name: GitHub Metrics

on:
  schedule:
    - cron: "0 0 * * *"  # once per day
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}  # classic token with repo + read:user

          # Output
          filename: github-metrics.svg
          output_action: commit

          # User info (do NOT include `repo:`!)
          user: Roshan1299
          template: classic
          base: header, activity, community, repositories, metadata

          # Plugins
          plugin_followup: yes
          plugin_followup_sections: user,repositories

          plugin_languages: yes
          plugin_languages_sections: most-used, recently-used
          plugin_languages_details: bytes-size, percentage
          plugin_languages_limit: 8
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 300
