name: GitHub Metrics

on:
  # Runs every day at midnight UTC
  schedule:
    - cron: "0 0 * * *"
  # Allows manual run from the Actions tab
  workflow_dispatch:

permissions:
  contents: write         # ✅ Required to commit the SVG to your repo
  actions: read
  checks: read
  deployments: read
  issues: read
  discussions: read
  pull-requests: read
  repository-projects: read
  security-events: read
  statuses: read

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub Metrics
        uses: lowlighter/metrics@latest
        with:
          # GitHub provides this automatically — no personal token needed
          token: ${{ secrets.GITHUB_TOKEN }}

          # Your GitHub username
          user: Roshan1299

          # Output file (default name is fine)
          filename: github-metrics.svg

          # Template and sections
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: America/Edmonton

          # 🧠 Plugins (feel free to add more)
          plugin_languages: yes
          plugin_languages_details: percentage
          plugin_languages_sections: most-used, recently-used
          plugin_languages_limit: 8
          plugin_languages_analysis_timeout: 15

          plugin_habits: yes
          plugin_habits_from: 200
          plugin_habits_days: 14
          plugin_habits_facts: yes
          plugin_habits_charts: yes

          plugin_followup: yes
          plugin_followup_sections: repositories, user
